### ISSUE TITLE
Support CSP without needing unsafe-eval

### ISSUE THREAD

**Issue by orwant** [google/google-visualization-issues#1356]
```
(No text was entered with this change)
```

Original issue reported on code.google.com by `None` on 1970-01-01T00:00:00.00Z

**Comment by emirotin** [comment]
This looks like a relevant issue. We started using CSP (currently in report mode only) and get a warning from https://www.google.com/uds/api/visualization/1.1/9543863e4f7c29aa0bc62c0051a89a8a/webfontloader,format+en,default+en,ui+en,table+en,corechart+en.I.js

> try{eval("document.namespaces")}catch(eKa){}R=dV[J];

**Comment by lweichselbaum** [comment]
The eval issue emirotin pointed out was actually located in Closure and was fixed by:
https://github.com/google/closure-library/commit/f5111ddff78324cccab92a211b41ed4c2fc6131c
For evals in GVIZ there should be a workaround soon.

**Comment by MichalStaruch** [comment]
@lweichselbaum @dlaliberte 

1. Google own secure coding policies for web applications (see CSP sections on [Web Fundamentals](https://developers.google.com/web/fundamentals/security/csp/), or [Chrome Extensions](https://developer.chrome.com/extensions/contentSecurityPolicy) portals) strongly recommends against using unsafe-eval. So does the [OWAS ASVS](https://www.owasp.org/index.php/Category:OWASP_Application_Security_Verification_Standard_Project) v3.0.1, requirement 11.7. Shouldn't Google be first to show people how to create good, secure APIs instead of forcing developers to break secure coding standards?
2. It's 2017 and we should cut off "browsers" like IE6 [unable to use JSON.parse()](http://caniuse.com/#feat=json) with [~1% market share](https://www.netmarketshare.com/browser-market-share.aspx?qprid=2&qpcustomd=0). It's time to move forward, if we want to have safer web.
3. Any chance to have this issue solved within next year/quarter/month?

**Comment by dlaliberte** [comment]
The 'current' version on the gstatic server avoids using eval, at least for loading.  See https://developers.google.com/chart/interactive/docs/basic_load_libs.

**Comment by lukas-lmt** [comment]
Using example from  https://developers.google.com/chart/interactive/docs/basic_load_libs I made two files one in php
```
<?php
header('Content-Security-Policy:'. 'default-src \'self\';'
    . ' font-src \'self\' https://fonts.gstatic.com;'
    . ' style-src \'self\' https://fonts.googleapis.com https://www.gstatic.com/charts/;'
    . ' script-src \'self\' https://www.gstatic.com/charts/');
?>
<head>
  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript" src="chart.js"></script>
</head>
<body>
  <!-- Identify where the chart should be drawn. -->
  <div id="myPieChart"/>
</body>
```
And second one in JS 
```
google.charts.load('current', {packages: ['corechart']});
google.charts.setOnLoadCallback(drawChart);

function drawChart() {
    // Define the chart to be drawn.
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Element');
    data.addColumn('number', 'Percentage');
    data.addRows([
        ['Nitrogen', 0.78],
        ['Oxygen', 0.21],
        ['Other', 0.01]
    ]);

    // Instantiate and draw the chart.
    var chart = new google.visualization.PieChart(document.getElementById('myPieChart'));
    chart.draw(data, null);
}
```

Header **'Content-Security-Policy** cause an error "Invalid JSON string: {}". Exactly this error is caused by **chart.draw(data, null);** .

So loading is not enough to use charts with CSP header without "unsafe-eval" directive

**Comment by dlaliberte** [comment]
Thanks Lukas.  This particular problem with null options should be easy for us to fix.  However, this particular complaint about the invalid JSON string seems largely irrelevant for any real vulnerability, so I am not understanding why it is considered a vulnerability.  If it merely suggests that, because of this error, there might be some other real vulnerabilities, that would be different, but I don't see how.  If we avoid this particular problem with a special check for the null options, then no JSON parsing would be involved, and only that special case would be taken care of, so we don't know about any other case.

**Comment by lukas-lmt** [comment]
Daniel thanks for fast response. This isn't problem with null options, using following JS: 
```
google.charts.load('current', {packages: ['corechart']});
google.charts.setOnLoadCallback(drawChart);

function drawChart() {
    // Define the chart to be drawn.
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Element');
    data.addColumn('number', 'Percentage');
    data.addRows([
        ['Nitrogen', 0.78],
        ['Oxygen', 0.21],
        ['Other', 0.01]
    ]);

    var options = {'title':'How Much Pizza I Ate Last Night',
        'width':400,
        'height':300};

    // Instantiate and draw the chart.
    var chart = new google.visualization.PieChart(document.getElementById('myPieChart'));
    chart.draw(data, options);
}
```
I have **Invalid JSON string: {"title":"How Much Pizza I Ate Last Night","width":400,"height":300}×** 

In my opinion library should work without "unsafe-eval" directive in any case because I am only user of library. And library users should be able to use it without additional exceptions.

**Comment by MichalStaruch** [comment]
@dlaliberte Could you please keep this issue opened until complete fix is released? It should be marked as solved when charts will be fully working without `unsafe-eval` (no exceptions at all).

**Comment by Flavien** [comment]
Why is this low priority? This is a major issue as the library can't be used on a web page that follows current security standards.

**Comment by NicolasCARPi** [comment]
Hello everyone, please don't let this issue die ;)

Have a nice day!

~Nico

**Comment by BenjaminEHowe** [comment]
This is affecting me too. Given how poor the practice of using "eval" is (and I don't see any mitigating factors in these circumstances) could this be considered a bug instead of an enhancement?

**Comment by Sora2455** [comment]
Here is Google's [own advice](https://developers.google.com/web/fundamentals/security/csp/#eval_too) on such matters:

> If eval and its text-to-JavaScript brethren are essential to your application, you can enable them by adding 'unsafe-eval' as an allowed source in a script-src directive, but **we strongly discourage this**. Banning the ability to execute strings makes it much more difficult for an attacker to execute unauthorized code on your site.

Emphasis mine.

It's not a good look for Google to say "use 'unsafe-eval' only when you absolutely have to - for example, when you need to support our code". Please fix this ASAP.

(Interestingly, the advice in that article for dealing with a library that uses eval is to switch to another library...)

**Comment by dlaliberte** [comment]
I am happy to report that this bug is now fixed in the 'current' version, v46.  There should be no further requirement for 'unsafe-eval'.

**Comment by dlaliberte** [comment]
The current version of Google Charts is v46, but you have to load it from the gstatic server as documented here:  https://developers.google.com/chart/interactive/docs/basic_load_libs#update-library-loader-code

In the near future (probably the next couple months), the jsapi loader will be redirected to the gstatic loader, and google.load() calls will also redirect to google.charts.load(), so that means everyone will be updated to v46.  See the announcement about this:  https://groups.google.com/forum/#!topic/google-visualization-api/hGys_iI99bE

**Comment by multiformeingegno** [comment]
This does not appear to be fixed.. I downloaded the loader from https://www.gstatic.com/charts/loader.js but when I load it I still see this in the console "Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source".

Specifically:
at eval (<anonymous>)
    at gvjs_xe (jsapi_compiled_default_module.js:57)
    at gvjs_nm.<anonymous> (jsapi_compiled_default_module.js:374)
    at gvjs_km (jsapi_compiled_default_module.js:354)
    at gvjs_nm.gvjs_.dispatchEvent (jsapi_compiled_default_module.js:352)
    at gvjs_sm (jsapi_compiled_default_module.js:361)
    at gvjs_nm.gvjs_.qua (jsapi_compiled_default_module.js:360)
    at gvjs_nm.gvjs_.kda (jsapi_compiled_default_module.js:360)

**Comment by dlaliberte** [comment]
Hi @multiformeingegno,

Can you provide more details about exactly what you are doing?  The error you report appears to be triggered by a Query response that does not match this pattern: /^({.*})$/.   This should normally not happen, so the question is, how is this happening for you?
