### ISSUE TITLE
Problem with query

### ISSUE THREAD

**Issue by foxhoundvenom** [google/google-visualization-issues#1976]
At first it worked and put the data vertically in each cell below the next.  Now it puts the data Horizontally.  The other cell I am referencing has Managers and regular Sales Reps.  I want to pull the Data from the form that is only the managers (which are listed under me), yet only show their Name, Ph #, and email that are in those rows.  So for example If I am their manager, my name shows in column B starting in Row 2 going down.  The Managers name and their info shows up in column L and moves Horizontally through Column U.  So If my name shows up in any cell in Column B it will populate only the managers info on one line, then the next manager on the next, and so on.  I believe my code is right because it did work, yet I left out a couple of columns.  When I corrected it to go through U it changed and will only show Data Horizontally like in the screenshot below.  Please help.  Thank you.

![screenshot 2015-05-12 14 48 43](https://cloud.githubusercontent.com/assets/3149091/7599374/538f546a-f8b6-11e4-8b68-ae9c8ad486fe.png)

**Comment by orwant** [comment]
I believe this is a question about Google Sheets, not Google Charts.

**Comment by foxhoundvenom** [comment]
It shows up under Google Charts with Google Sheets.

**Comment by orwant** [comment]
I'm having trouble understanding exactly what the issue is. For instance, I can't tell what the "it" is that you refer to in your post. If you have a Google Sheet, and then select "Insert Chart...", and then can identify a bug in the generated chart, that's where we can help.  Until there is a specific technological problem that's been identified, questions about general usage are better suited to our forum anyway: https://groups.google.com/forum/#!forum/google-visualization-api. 

Sorry to not be able to help more.
