### ISSUE TITLE
Line chart:  x axis data column type is date but i want the x axis to be discrete.

### ISSUE THREAD

**Issue by Amarjit1234** [google/google-visualization-issues#1986]
I am using a google chart where x axis data column type is date. But i want the x axis to be discrete. Is there any way to accomplish this.

**Comment by grabks** [comment]
Yes, this is possible. All you have to do is change the 'type' option of the axis to be 'category'. Here is an example: https://jsfiddle.net/o02vw4L5/

In the future, please post questions about using our library [on the forum](https://groups.google.com/forum/#!forum/google-visualization-api), instead of filing an issue.

**Comment by Amarjit1234** [comment]
Thank you so much for comment. But when I changed the 'type' option of the axis to 'category'. trendlines is not showing.

Here is the code:

 google.load('visualization', '1.1', {packages: ['corechart']});
  google.setOnLoadCallback(drawChart);

   function drawChart() {

```
var revenueChart_93;    

var data = new google.visualization.DataTable();

   data.addColumn('date', 'Month');   
   data.addColumn('number', 'Predicted Grade');      
   data.addColumn('number', 'Working Grade');
   data.addColumn('number', 'Estimated Grade');


data.addRow([new Date(2015, 2, 12),  1.0,  1.0,  1.0 ]);
data.addRow([new Date(2015, 5, 12), 4.5, 5.0, 6.5]);
data.addRow([new Date(2015, 6, 1), 5.0, 6.0, 4.5]);
data.addRow([new Date(2015, 11, 1), 6.5, 7.0, 5.0]);


var formatter = new google.visualization.NumberFormat({
    fractionDigits: 2,     
});
formatter.format(data, 1);
var dateFormatter = new google.visualization.NumberFormat({
    pattern: 'yyyy MMM'
});
dateFormatter.format(data, 0);
var chartHeight = 550;
var chartWidth = 750;
var chartOptions = {
    trendlines: {
        1: {
            color: 'yellow',
    //tooltip: false
        }
    },
    title: 'Progress Report',
    isStacked: true,
    width: chartWidth,
    height: chartHeight,      
    hAxis: {
        title: 'Year',
        slantedText: true,
        slantedTextAngle: 45,
        textStyle: {
            fontSize: 10
        },
        format: 'MMM yyyy', 
    },
    vAxis:{title: "Grade",
            minValue: 1,
            maxValue: 10, 
            gridlines: {
            count: 19
            },
            baselineColor: 'none',


            },       
    series: {
        2: { lineDashStyle: [2, 2] },
         },
 legend: { position: 'right', alignment: 'start' },

};
```

   revenueChart_93 = new   google.visualization.LineChart(document.getElementById('progress'));
    revenueChart_93.draw(data, chartOptions);
}

<div id="progress"></div>

**Comment by grabks** [comment]
This is expected behavior. Trendlines do not work for 'category' domain axes. I suppose that it might make sense to have trendlines work on a "per-unit" basis, but for now this behavior is intentional, and you should use a value axis if you want trendlines. I think the bigger question here is why do you want both a discrete axis and trendlines? What exactly are you trying to convey?

**Comment by dan-corneanu** [comment]
I did struggle with a similar issue for a couple of days. Is this options mentioned/documented anywhere on the Google Charts documentation?
https://developers.google.com/chart/

I was not able to find a single mention of it.

**Comment by shelbykauth** [comment]
I know this is super late and stuff.  But Use Case:

I'm working with dates.  But I want to display every label (let's call it every day) and I want to have the bar stretch from the beginning of a time period to the end of a time period, rather than displaying 5 labels for 13 data points with 'March 3rd' stretching from noon on March 2nd to noon on March 3rd (when it really represents 3/3 at 0:00 to 3/3 at 23:59).  So I convert the dates into discreet strings and fill in any gaps with 0's.

But then I'm asked to stick a trendline on it.
