### ISSUE TITLE
Customizing Points conflict with legend bottom overflow in line chart

### ISSUE THREAD

**Issue by VishmayShah** [google/google-visualization-issues#2017]
google charts
version:1.1 Specific

  pointSize: 7,
  legend: 'bottom',

will have legend with datapoint symbol of circle/triangle whatever

if you have more than 5 or 10 series, then legend has pagination < 1/3 >
if Customizing points are on pagination then prev and next arrows ("<", ">") are enlarged
if  you change version 1.1 to 1.0 then arrow are at good size but legend symbols are simple

**Comment by dlaliberte** [comment]
Thanks.  We noticed this recently as well, and it will be fixed in the next
release, which should be in about a month.

On Wed, Aug 5, 2015 at 7:05 AM, VishmayShah notifications@github.com
wrote:

> google charts
> version:1.1 Specific
> 
> pointSize: 7,
> legend: 'bottom',
> 
> will have legend with datapoint symbol of circle/triangle whatever
> 
> if you have more than 5 or 10 series, then legend has pagination < 1/3 >
> if Customizing points are on pagination then prev and next arrows ("<",
> ">") are enlarged
> if you change version 1.1 to 1.0 then arrow are at good size but legend
> symbols are simple
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/google/google-visualization-issues/issues/2017.

## 

Daniel LaLiberte https://plus.google.com/100631381223468223275?prsrc=2  -
978-394-1058
dlaliberte@Google.com dlaliberte@google.com   5CC, Cambridge MA
daniel.laliberte@GMail.com daniel.laliberte@gmail.com 9 Juniper Ridge
Road, Acton MA
