### ISSUE TITLE
Linechart legend box/line change

### ISSUE THREAD

**Issue by nexbridge** [google/google-visualization-issues#2027]
Hi there,

The default legend styling on the linechart/corechart package has changed this morning (18/08/2015) in that instead of a box corresponding to each colour it's now a line.  It's the API that's changed as I haven't changed anything, and I can't see how to change it back!

Thanks,

Philip

**Comment by danabnormal** [comment]
Are you loading version '1' of the chart in your code? If so try changing it to '1.0' and see if that works (ie google.load('visualization', '1.0', { 'packages': ['table'] }); ). I had issues (not the same as yours) this morning and that fixed it for me.

**Comment by nexbridge** [comment]
Yes thank you, that fixed it!

**Comment by grabks** [comment]
@nexbridge @danabnormal What you are doing is a temporary stopgap at best. I encourage both of you to become familiar with [our release process](https://developers.google.com/chart/interactive/docs/release_notes?hl=en#the-google-visualization-api--release-process-and-release-candidates). To summarize it, we first push a release to '1.1', with '1' pointing to '1.0', switch '1' to point to '1.1', then push the release in '1.1' to '1.0'. **Using version 1.0 will only fix the issue until we push the release to 1.0, causing you to catch problems later.**

If there is an issue with a release, please post on the forum to make us aware of it instead of simply switching the version. We recommend that all users either load '1', '1.1', or at least regularly test the '1.1' release on their pages.

To specifically respond to this bug: this is an intentional change, intended to make it easier to distinguish between different types of series. Take a look at [this jsfiddle](http://jsfiddle.net/gw03m8to/) for a good example of this feature being useful. If there is some way we could improve this behavior, instead of just reverting to the old behavior, we'd prefer to do that.

While **we expect to eventually deprecate this option**, if you _really_ want the old behavior, you can use the `legend.newLegend` option to turn it off. You can see an example of using it [here](http://jsfiddle.net/gw03m8to/1/).

**Comment by danabnormal** [comment]
Hi @grabks . I did actually post about the issue I was having (together with screenshot) on the Google Charts discussion board. The problem is that if we are using version '1' in Production and it changes (as seems to have happened), any issues related to the 'new' version then come out in live web pages. Reverting to 1.0 was the only way for me to get expected behavior and a functioning site in this instance.

**Comment by nexbridge** [comment]
Thanks for the explanation @grabks.  The impact for us was similar to that of @danabnormal in that it affected live web pages without warning.  Personally I prefer the boxes to the lines, as they look better and take up less horizontal space, which screwed up my graph rendering.  Would it be possible to retain your improved behaviour (whatever that is) in the new version whilst offering an option to have either a line or a box as the legend icon?

**Comment by grabks** [comment]
@danabnormal I completely understand that breaking issues will occur at some point, but changing to '1.0' isn't going to fix anything long-term, since we will push the 1.1 release to 1.0 soon, and you will see the same issues you're seeing now, except there won't be a "more stable" thing you can switch to.

I can't find your thread anywhere, nor your screenshot, although a screenshot is generally not enough for us to debug an issue, since most people's issues stem from them doing something very specific that we didn't account for. Ideally, we need a live page in order to debug an issue. A jsfiddle reproducing the issue would also work. **If we don't get a reproducible case, we can't fix the issue by the time we push to 1.0 and you will start seeing the issue again.**

If you'd like to not deal with these issues (but also not get any new features), you can start using our [frozen versions](https://groups.google.com/d/msg/google-visualization-api/hBCwxtXYNZ8/_YUb4YVI6psJ) which were announced just recently.

**Comment by danabnormal** [comment]
Hey @grabks . I know a fiddle is normally preferred, however at the time (as you can imagine) I had my fire hose in hand so wanted to post something quick - I believe my post was removed for some reason however you can see the response I posted to the announcement copied in Daniels 3rd post at https://groups.google.com/forum/#!topic/google-visualization-api/XxP1zYbWQRE .

I have read with interest your move to frozen versions and was planning on testing them environments further - I just ran out of time as (unless I missed something) there didn't seem much notice that this change was incoming.

Cheers for your help though!

**Comment by grabks** [comment]
@nexbridge If you're simply worried about the horizontal space, you can play around with the aspect ratio of the icons (`legend.iconAspectRatio`) to find a good compromise. We might have been a bit aggressive, setting the default to 2. [Here's an example of using that option.](http://jsfiddle.net/gw03m8to/2/)

**Comment by grabks** [comment]
@danabnormal The changes have been in 1.1 for around 3 months now, since April 30th. We recently considered it to be stable enough (because we didn't hear about any bugs) to move to the pre-production stage (making '1' point to '1.1') to get more people to test the changes.

We give a lot of opportunities to test the coming changes, but if everyone switches to 1.0, then they won't become aware of these issues until we push to stable.

**Comment by nexbridge** [comment]
@grabks Thanks again - is there an up-to-date reference manual with all the available options in it - only the one I was looking at below doesn't have <code>legend.iconAspectRatio</code> or <code>legend.newLegend</code>:

https://developers.google.com/chart/interactive/docs/gallery/linechart?hl=en

**Comment by grabks** [comment]
We will probably never document `legend.newLegend`, given our intent to deprecate it; the fewer people use it, the better. `legend.iconAspectRatio` is a new option and we simply haven't gotten around to documenting it. I've filed an internal bug to do this, so you should see the documentation change fairly soon.
