### ISSUE TITLE
IE8: Unable to get property 'length' of undefined or null reference

### ISSUE THREAD

**Issue by mauhiz** [google/google-visualization-issues#2055]
Happens on all graphs I tried (pie, clustered bars, stacked bars).

The table data is fed with a JS object. There is no trailing comma.

The error is thrown in a function that looks (minified...) like this : 

``` javascript
function oQa(a,b,c){for(var d=a.Ok+a.Qu,e=a.gc[od]-a.gc[F]-d,f=a.Ta[Ic],g=k[B](f/1.618),h=k[B](f/3.236),l=f+g,n=f+h,f=[],h=0,q=k[B](a.gc[F]),t=0;t<c[I];t++){var v=c[t],x=b[t][I];if(0!=x){var A=KT(a.Xd,v[td],a.Ta,e,x),x={};x.id=v.id;x.Ja={text:v[td],la:a.Ta,Hr:null,N:[],anchor:new tV(q,0),Pc:EE,Qc:EE,sa:A.Ce?v[td]:L,Ib:0};x.sc={};hz(x.sc,new Em(q,h,a.Ok,a.mJ));x.sc.brush=v.brush[Lc]();a.Ta.Vb&&x.sc.brush.pd(a.Ta.Vb,1);x.ba=!0;for(var C=0;C<A.N[I];C++)0<C&&(h+=n),x.Ja.N[z]({x:d,y:h,length:e,text:A.N[C]});
```

when accessing `b[t][I]`

Since I have no idea what this does, I am not sure what setting to try tweaking.

The only other loaded library is jQuery-1.11.1. Removing it did not seem to help.

Using es5-shim or other shims did not help.

**Comment by Aydie** [comment]
these "very helpful" messages usually occur if you draw the chart on an invisible div, so it can't calculate the size

----- Ursprüngliche Nachricht -----
Von: "Vincent PÉRICART" notifications@github.com
Gesendet: ‎17.‎09.‎2015 08:09
An: "google/google-visualization-issues" google-visualization-issues@noreply.github.com
Betreff: [google-visualization-issues] IE8: Unable to get property 'length' ofundefined or null reference (#2055)

Happens on all graphs I tried (pie, clustered bars, stacked bars).
The table data is fed with a JS object. There is no trailing comma.
The error is thrown in a function that looks (minified...) like this : 
function oQa(a,b,c){for(var d=a.Ok+a.Qu,e=a.gc[od]-a.gc[F]-d,f=a.Ta[Ic],g=k[B](f/1.618),h=k[B](f/3.236),l=f+g,n=f+h,f=[],h=0,q=k[B](a.gc[F]),t=0;t<c[I];t++){var v=c[t],x=b[t][I];if(0!=x){var A=KT(a.Xd,v[td],a.Ta,e,x),x={};x.id=v.id;x.Ja={text:v[td],la:a.Ta,Hr:null,N:[],anchor:new tV(q,0),Pc:EE,Qc:EE,sa:A.Ce?v[td]:L,Ib
 :0};x.sc={};hz(x.sc,new Em(q,h,a.Ok,a.mJ));x.sc.brush=v.brush[Lc]();a.Ta.Vb&&x.sc.brush.pd(a.Ta.Vb,1);x.ba=!0;for(var C=0;C<A.N[I];C++)0<C&&(h+=n),x.Ja.N[z]({x:d,y:h,length:e,text:A.N[C]});when accessing b[t][I]
Since I have no idea what this does, I am not sure what setting to try tweaking.
The only other loaded library is jQuery-1.11.1. Removing it did not seem to help.
Using es5-shim or other shims did not help.

**Comment by mauhiz** [comment]
@Aydie thanks for the hint, but the div is certainly visible in this case (it has preset width and height); also `height`, `width`, `chartArea.height`, `chartArea.width` did not make a difference.

**Comment by grabks** [comment]
@Aydie actually, drawing in an invisible div generally causes rendering errors, not exceptions.

@mauhiz Unfortunately, it's not especially helpful to point us at the minified code. Could you either create a jsfiddle or attach an HTML page that demonstrates the failure?

**Comment by Aydie** [comment]
@grabks actually I can show you quite a number of exceptions caused by drawing on invisible divs, as i had to code around it due to using accordions

----- Ursprüngliche Nachricht -----
Von: "grabks" notifications@github.com
Gesendet: ‎17.‎09.‎2015 15:41
An: "google/google-visualization-issues" google-visualization-issues@noreply.github.com
Cc: "Aydie" alexander.pill@gmail.com
Betreff: Re: [google-visualization-issues] IE8: Unable to get property'length' of undefined or null reference (#2055)

@Aydie actually, drawing in an invisible div generally causes rendering errors, not exceptions.
@mauhiz Unfortunately, it's not especially helpful to point us at the minified code. Could you either create a jsfiddle or attach an HTML page that demonstrates the failure?

**Comment by grabks** [comment]
@Aydie Really? I'd really appreciate seeing an example of one. Which browsers do they occur in? I've certainly never seen one in Chrome.

**Comment by grabks** [comment]
@Aydie Wait, do you mean invisible divs or non-existing divs? Because we definitely do throw an exception if you hand it an element that doesn't exist. But rendering in invisible divs (display: none, or visibility: hidden) should only produce rendering errors.

**Comment by Aydie** [comment]
@grabks i have to verify it, but i definitely had problems with your very meaningful exceptions using jquery accordions and -tabs

----- Ursprüngliche Nachricht -----
Von: "grabks" notifications@github.com
Gesendet: ‎17.‎09.‎2015 15:48
An: "google/google-visualization-issues" google-visualization-issues@noreply.github.com
Cc: "Aydie" alexander.pill@gmail.com
Betreff: Re: [google-visualization-issues] IE8: Unable to get property'length' of undefined or null reference (#2055)

@Aydie Wait, do you mean invisible divs or non-existing divs? Because we definitely do throw an exception if you hand it an element that doesn't exist. But rendering in invisible divs (display: none, or visibility: hidden) should only produce rendering errors.

**Comment by mauhiz** [comment]
@grabks While minimizing, I found the cause of the error message; a custom shim for Array.map that relies on jQuery:

``` javascript
  if (!Array.prototype.map) {
    Array.prototype.map = function(callback, thisArg) {
      return $.isArray(thisArg) ? $.map(thisArg, callback) : [];
    };
  }
```

Not sure why that make things fail. As many others suggested, it would be so helpful if there was a way to browse the JS sources ;)

By the way, I still cannot see graphs on IE8 but this is another issue.

**Comment by grabks** [comment]
@mauhiz Hmm. I'm not sure how that would cause things to fail, but if you need to define Array.prototype methods when they're not available, you might have better luck using the polyfills in [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map).
