### ISSUE TITLE
IE8 mode: Graphs are not shown

### ISSUE THREAD

**Issue by mauhiz** [google/google-visualization-issues#2056]
It is quite hard to obtain a real IE8 these days so I am relying on the IE8 mode of IE11, which may be the actual issue...

Here is a minimized version of the issue:

``` html
<html>
    <body>
        <p>Before graph</p>
        <script type="text/javascript" src="https://www.google.com/jsapi"></script>
        <div id="q1" style="width: 500px; height:500px;">This should be replaced</div>
        <script type="text/javascript">
            google.load("visualization", "1.1", {
                packages: [ "corechart" ]
            });
            google.setOnLoadCallback(function() {
                var data = new google.visualization.DataTable({
    "cols": [{
        "type": "string",
        "label": "some label"
    },
    {
        "type": "number",
        "label": "test"
    }],
    "rows": [{
        "c": [{
            "v": "some entry"
        },
        {
            "v": 10
        }]
    }]
});
                var targetDiv = document.getElementById('q1');
                var chart = new google.visualization.BarChart(targetDiv);
                chart.draw(data);
            });
        </script>
        <p>After graph</p>
    </body>
</html>
```

**Comment by grabks** [comment]
I copied the exact page you gave into a page on an IE8 VM from [dev.modern.ie](https://dev.modern.ie/), and everything appears to work like you would expect.

Here's a screenshot from the IE8 VM:
![screen shot 2015-09-18 at 10 01 03 am](https://cloud.githubusercontent.com/assets/11892394/9961487/d1c393ee-5dee-11e5-82a1-d99c20d437d4.png)

Testing with IE11, and setting the document type to IE8 does produce an empty page, but I'd guess that's only because it drops into Quirks mode (which we do not support). You might be able to get around this issue by specifying `<!DOCTYPE html>` at the top of the HTML file, but I wasn't able to.

**Comment by mauhiz** [comment]
Thanks, confirmed. Knowing that Quirks Mode is not supported helped a lot!
