### ISSUE TITLE
Bar chart: bars disappear on hover when redrawing with different chart types

### ISSUE THREAD

**Issue by hannujaakkola** [google/google-visualization-issues#2065]
If you draw a Bar chart and hover over or click a bar element (so that the tooltip is shown) and then redraw the chart as a ColumnChart and draw the chart again as a Bar chart the bars and tooltip containers disappear when hovering over them.

JSFiddle: https://jsfiddle.net/ngwfjkbf/

Note: in our case we sometimes have to change from a bar chart to a stacked bar chart (only possible as a ColumnChart) so multiple chart types are needed.

**Comment by grabks** [comment]
Wow, that's an annoying bug. Sorry for the inconvenience that this is causing you.

This bug is actually fixed in our next release (version 43), which we should push sometime next week.

About your second note, though, Bar charts do actually support stacking, but you wouldn't see that with the ChartWrapper since it doesn't do option conversion. You should be able to call chart.setOptions(google.charts.Bar.convertOptions({isStacked: true})) and have it work.
