### ISSUE TITLE
Not able to draw two charts of same type

### ISSUE THREAD

**Issue by syedhassan** [google/google-visualization-issues#2085]
Refer this jsfiddle
https://jsfiddle.net/qb16cygb/

I am here trying to draw charts of the same types but it only draws the second chart and not the first! Shouldn't it draw both?

**Comment by grabks** [comment]
This has been fixed with release 43. However, we have been having issues with pushing the 43 release to /jsapi. Currently, the release is only available while using the [frozen loader](https://developers.google.com/chart/interactive/docs/library_loading_enhancements#frozen-versions)

[Here's a version of your jsfiddle that was modified to load frozen 43.](https://jsfiddle.net/qb16cygb/1/)

**Comment by syedhassan** [comment]
@grabks thanks a ton!
