### ISSUE TITLE
Incorrect Map of India

### ISSUE THREAD

**Issue by madhusasinair** [google/google-visualization-issues#2120]
In the Geo Charts, incorrect map of India is showing as highlighted in the attachment. While major part of the maps are highlighted in Dark Green color, parts of Kashmir and Arunachal Pradesh are greyed out.Please explain the reason behind this.

When showing map of any country you are supposed to show the official map of the country and not of the political map your country follows.

![google india](https://cloud.githubusercontent.com/assets/16099830/11499974/fe2fe54a-984f-11e5-9e9e-345cce29ff36.png)

**Comment by orwant** [comment]
Google does not make editorial decisions about geopolitical boundaries. We follow international standards, except in some instances where local laws differ. That is the case in India for Kashmir, which is why when you specify the IN locale when rendering a Geochart, you'll see the map you want.

Peace,
Jon

**Comment by madhusasinair** [comment]
I am seeing a map sans whole of Kashmir. If you could check a REAL map of India you will come to know of the  difference.
