### ISSUE TITLE
Firefox - legend not shown when using addColumn

### ISSUE THREAD

**Issue by jitbit** [google/google-visualization-issues#2171]
This code does not show legend in Firefox (Edge and Chrome work fine) in Area charts

```
var data = new google.visualization.DataTable();
data.addColumn('string', 'Column1');
data.addColumn('number', 'Column2');
ata.addRows(['test', 1]);
```

This code DOES show the legend, but I need the first version!

```
var data = google.visualization.arrayToDataTable([
            ['Column1', 'Column2'],
            ['test', 1]]);
```

**Comment by grabks** [comment]
@jitbit I would guess that this is due to your using `DataTable.addRows` instead of `.addRow`. Here is [a jsfiddle](http://jsfiddle.net/w3v9nLr9/) that generates two charts, one with data generated using your first method, and the other generated using your second method.

I tested this jsfiddle both in Chrome and Firefox on OS X and both charts rendered as expected. Can you please provide a jsfiddle that breaks for you?

**Comment by jitbit** [comment]
Indeed, I just cropped the code to one line incorrectly... Anyway, it was something else, I'm closing the issue, terrbily sorry for the false alarm. Thanks @grabks . Sorry again.
