### ISSUE TITLE
Combo Chart size doesn't change

### ISSUE THREAD

**Issue by limkukhyun** [google/google-visualization-issues#2172]
Eng :  in bootstrap, Combo chart size doesn't change. tab-pane (with active) it works good, but tab-pane (without active) not good.

Kor : Bootstrap 사용중입니다. bootstrap의 tab-pane이 active 되어있는 tab에서 사용할땐 문제 없는데 active 되어있지 않은 tab에 combo chart를 넣고 active 시키면 combo chart의 크기가 고정된 상태로 안바뀝니다.

![2016-02-14 01 14 50](https://cloud.githubusercontent.com/assets/2470696/13028661/7d6200da-d2b8-11e5-910f-4dc8055dbef3.png)

**Comment by dlaliberte** [comment]
This appears to be the old problem caused by drawing the chart when it is not visible, so text appears to take up no space and everything will be more compressed than it should be.  The workaround is to arrange that you only draw the chart when it is visible.  Since that workaround is usually possible, we are not strongly motivated to find a solution that allows you to draw charts when they are not visible.
