### ISSUE TITLE
Multiple Charts on a Single Webpage working in (41, 42, 43) not anymore in 44

### ISSUE THREAD

**Issue by ruben-pieters** [google/google-visualization-issues#2179]
Hey,

The issue described in https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/google-visualization-api/KulpuT418cg/yZieM8buCQAJ reappears for me when using the '44' version of google charts.

Fiddle with '44' (not working): https://jsfiddle.net/bzs1pLvo/

Fiddle with '41' (working): https://jsfiddle.net/3qdxd2m9/2/

**Comment by grabks** [comment]
@ruben-pieters Thank you for your report. This appears to be caused by [issue #309](https://github.com/typekit/webfontloader/issues/309) in the WebFontLoader. We'll attempt to fix version 44 by using an older version of WebFontLoader, but in the meantime you can work around this either by loading version 43, or by putting `setTimeout`s around your `chart.draw` calls, which seems to work around the issue. However, that fix is a bit painful, since you would have to nest the `setTimeout`s in order for it to work ([like this](https://jsfiddle.net/f3t4rokk/)).

**Comment by grabks** [comment]
Alternatively, you could draw the charts in sequence, when you get the ready event, like so: https://jsfiddle.net/p3po78o1/

**Comment by grabks** [comment]
We have replaced the version of WebFontLoader in version 44 with the version we used in 43 (that was found to be more stable), so this issue should now be resolved.
