### ISSUE TITLE
Fiddles are broken

### ISSUE THREAD

**Issue by moshfeu** [google/google-visualization-issues#2195]
In this page https://developers.google.com/chart/interactive/docs/gallery/steppedareachart the demos are not shown so the fiddle who likns to.

For example:

https://jsfiddle.net/api/post/library/pure/

**Comment by grabks** [comment]
In order to share a fiddle with someone, you first have to save it to generate a new link. The link you posted doesn't point to a unique fiddle. Here is a fiddle I saved from the first example on the page you linked to: https://jsfiddle.net/sxycpgp0/

**Comment by moshfeu** [comment]
Your jsfiddle doesn't show anything too.

Can you see the demos in the page I posted? (https://developers.google.com/chart/interactive/docs/gallery/steppedareachart)

**Comment by grabks** [comment]
Yes, I can.

It sounds like you are experiencing the issues caused by caching and propagation delays of our latest release. These issues should fix themselves eventually. In the meantime, you can workaround it by explicitly specifying a version, such as '43' or '44' instead of 'current' or 'upcoming' as you currently do. If this workaround does not fix your problem, please post back with a code sample.

This bug is a duplicate of #2185.
