### ISSUE TITLE
Can't print properly a responsive chart

### ISSUE THREAD

**Issue by JulienMaille** [google/google-visualization-issues#2252]
I have followed the recommendations in order to add responsiveness to my chart.
They now resize properly with the viewport.
However when trying to print, the chart is too large and cropped.
I have tried to detect the "aboutToPrint" event and call the redraw but it doesn't solve the issue.

An example of responsive chart can be fount here:
http://jsfiddle.net/toddlevy/pyAz5/
If you try to print this: http://fiddle.jshell.net/toddlevy/pyAz5/show/light/ you will see the problem.

**Comment by dlaliberte** [comment]
From your description, it sounds like the container for your chart is too large when you try to print the chart.  It could be that the way you make your container responsive, with width and height set to 100%, causes the problem when the image is generated because it starts with the same dynamic container sizing rather than fixing it to the current size of the chart container at the time you create the image. 

If you want to keep using the 100% sizing, I would suggest adding another wrapper around the chart for that purpose, and then in your resize handler, set the size of the chart container to the current size of the wrapper.

**Comment by JulienMaille** [comment]
Bonsoir @dlaliberte 
Could you kindly elaborate on your suggested fix? If you have a look at the fiddle, you will see there is already a wrapper around the chart. I tried adding:
`$('#visualization').width($('#visualization_wrap').width());
$('#visualization').height($('#visualization_wrap').height());`
before redrawing the chart but I don't see any change.
Look [here](http://jsfiddle.net/pyAz5/314/) and try to print fullscreen [here](http://fiddle.jshell.net/pyAz5/314/show/light/)

**Comment by dlaliberte** [comment]
I started with your code and made several changes to try to narrow it down.  http://jsfiddle.net/dlaliberte/bpp6psy5/3/

It seems to update fine for the width, but the height is not correct.  Close enough to demonstrate the problem.

As long as the size is dynamically set, the generated chart image always appears to get a larger size so then it draws outside the wrap container with the border.    Setting the width to a fixed number in the resize handler allows the chart image to be generated correctly.  So this is still a mystery to me.  Even if I set the size initially fixed, the dynamic resizing does kick in when generating the image, and it gets the wrong size.
