### ISSUE TITLE
DataTable mangles date input

### ISSUE THREAD

**Issue by TRManderson** [google/google-visualization-issues#2276]
In certain situations, DataTable will inexplicably increment the month of a date passed to the constructor of DataTable. The input provided below is an example of input that becomes mangled.

``` json
{
    "cols":[
        {"type":"date","id":"date","label":"Date"},
        {"type":"number","id":"value","label":"Value"}
    ],
    "rows":[{"c":[{"v":"Date(2016, 5, 5)"},{"v":1}]}]
}
```

**Comment by TRManderson** [comment]
Appears to be the same issue as #2259 and #2275

**Comment by dlaliberte** [comment]
The month indices start at 0, so this data does not demonstrate what might be a possible problem with dates.  The month with index 5 is June, so your date should be June 5, 2016, and that is what I see when I create a chart using it.

**Comment by TRManderson** [comment]
DataTables seems to maliciously increment the month when using the old JS loader. Switching to the new JS fixes this, but it's kind of a dick move.

**Comment by dlaliberte** [comment]
It was certainly not intentional.  It was a bug introduced by me when I
changed how we construct dates from the date strings to be less
vulnerable.  It only has this side effect of changing the date when the
current date is the last couple days of some months, so it was difficult to
anticipate this situation.

On Tue, May 31, 2016 at 8:31 PM, Tom Manderson notifications@github.com
wrote:

> DataTables seems to maliciously increment the month when using the old JS
> loader. Switching to the new JS fixes this, but it's kind of a dick move.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> https://github.com/google/google-visualization-issues/issues/2276#issuecomment-222860860,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAizDR15JhDC5jM_WoP9eDiWtqAwX2bFks5qHNLTgaJpZM4IqMwJ
> .

## 

Daniel LaLiberte https://plus.google.com/100631381223468223275?prsrc=2
dlaliberte@Google.com dlaliberte@google.com   5CC, Cambridge MA
