### ISSUE TITLE
vAxes was broke in 2 lines, and was shifted while browser height was changed.

### ISSUE THREAD

**Issue by nealshan** [google/google-visualization-issues#2331]
Hey guys,  
ENV:
WIN7, chrome 51.0.2704.103 m

I put my code on jsFiddle , but jsFiddle can't show it in full screen, so I also put code on Plunker
[go to jsFiddle](https://jsfiddle.net/shandeai520/zx82c14a/4/) 
[go to Plunker](http://plnkr.co/edit/scoquDJqtr5gJPRhtfEH?p=preview)

Reproduce step:
1. go to Plunker and click preview to show the result page in full screen
2. drag window's bottom line up and down, you will see legend was shifting. and separated

---

Please help to take a look at this, any comments will be appreciated.
1. why it was separated to 2 lines?
2. can we force it to use one line?
3. if not, can we force them not shift, the (Number) should be at right.

![image](https://cloud.githubusercontent.com/assets/9512651/17352546/e8a5491e-5969-11e6-8300-06ce55c791ad.png)    

**After browser height was changed, two lines shifted.**     

![image](https://cloud.githubusercontent.com/assets/9512651/17352579/284b04c8-596a-11e6-87d5-4d76f9a7f3dc.png)

**Comment by nbering** [comment]
What browser and version did you see this in? Does it happen in other browsers? What version of the API are you loading? Looks like some quirk in how the browser renders SVG. It would probably help the charts team if you could also submit a jsFiddle that can reproduce the bug.

**Comment by nealshan** [comment]
@nbering thanks for your guide, I 've updated my description with jsFiddle and Plunker

**Comment by nbering** [comment]
I was able to replicate the issue with your plunker example in Chrome on OS X. I don't know exactly what the cause is, but I know the angular adapter layer pretty well. The chart is redrawn on every window resize event, and for some reason, once you get to a certain width, it seems to flip-flop between one or the other on top. Looking at the numbers for the coordinates and rotation of the text elements involved, feels like it might just be a rounding error or something. Not much I can do about it, just reporting that I could reproduce it.

**Comment by nealshan** [comment]
@nbering thank you so much, from your idea of re-drawn, I tried to increase my height one px for each resize, from 250px to 255 px, it was fixed, at least it was one line now, no flip-flop any more.
So I think if someone else has this issue, they could increase their height to fix the flip-flop issue first.

Added 255px example on plunker.
