### ISSUE TITLE
AnnotatedTimeline stopped working

### ISSUE THREAD

**Issue by LawrenceMok** [google/google-visualization-issues#2355]
Yesterday the API is still working, but today, the API throws two errors and does not display any chart at all

From Chrome Console:

Uncaught ReferenceError: gvjs_6Y is not defined - https://www.gstatic.com/charts/45/js/jsapi_compiled_annotatedtimeline_module.js

Uncaught TypeError: google.visualization.AnnotatedTimeLine is not a constructor -
debugger:///VM36 report.php

**Comment by dlaliberte** [comment]
Thanks for reporting this.  

As I posted today on the google-visualization-api list, we are replacing the AnnotatedTimeline chart with the AnnotationChart.  However, it should be automatically redirecting to use the new chart, but that is failing to happen, which I will investigate and fix.  

In the meantime, you can switch to using the AnnotationChart yourself.  Just load the 'annotationchart' package, and call new google.visualization.AnnotationChart instead of AnnotatedTimeline.  Everything else should be the same.

**Comment by dlaliberte** [comment]
Should all be working again, with the new AnnotationChart automatically used instead of the old AnnotatedTimeline.

**Comment by lury** [comment]
in my case it's not working but info provided here was enough to fix the issue.

**Comment by dlaliberte** [comment]
I made a mistake in my tests, so annotatedtimeline is still not autoloading the annotationchart.  I'll have a fix for that shortly.
