### ISSUE TITLE
HTML Axes Label

### ISSUE THREAD

**Issue by oatto** [google/google-visualization-issues#2427]
Is there anyway to display label in axes as HTML or image ?

If it is not possible, is there another library which has this feature ?

Thank you in advance.

**Comment by nbering** [comment]
You should be able to use the chart layout interface the position an element relative to the axis. Here's the relevant guide, but the the element positioned inside.

https://developers.google.com/chart/interactive/docs/overlays

I made an example using this with angular-google-chart that positions a weather icon above the bars in a combo chart. It's a pretty powerful feature for handling all the custom flair that a basic chart would never know it needed to handle.

Here's that sample. It uses Angular, but I just link it here because it demonstrates the concept.
http://codepen.io/nbering/pen/yNZxKr

**Comment by oatto** [comment]
@nbering Thanks a lot !
