### ISSUE TITLE
Charts timeline months wrong

### ISSUE THREAD

**Issue by nmccollum** [google/google-visualization-issues#2448]
Load:
  google.charts.load("current", {packages:["timeline"]});

Insert row:
    [ '65175', new Date(2016,12,30,20,09,27), new Date(2017,01,04,18,02,46) ],

The data is displayed minus one month, so 00 is January, 12 is November.

`<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<script type="text/javascript">
  google.charts.load("current", {packages:["timeline"]});
  google.charts.setOnLoadCallback(drawChart);
  function drawChart() {

    var container = document.getElementById('Jobs');
    var chart = new google.visualization.Timeline(container);
    var dataTable = new google.visualization.DataTable();
    dataTable.addColumn({ type: 'string', id: 'JobID' });
    dataTable.addColumn({ type: 'date', id: 'Start' });
    dataTable.addColumn({ type: 'date', id: 'End' });
    dataTable.addRows([
    [ '65175', new Date(2016,12,30,20,09,27), new Date(2017,01,04,18,02,46) ],
    [ '65176', new Date(2016,12,30,20,09,36), new Date(2017,01,03,09,59,50) ]]);
    var options = {
      timeline: { colorByRowLabel: true }
    };
  
    chart.draw(dataTable, options);
  }

</script>

<div id="Jobs" style="height: 500px;"></div>`

Notice that the date in the code, then mouse over the table.  Off by one.

**Comment by dlaliberte** [comment]
All numbers provided to the Date constructor are 0 based except for the day of the month.  So the month number is 0 based, and 0 is January.  This is common across many programming languages.

Also note that you should not use a 0 prefix for decimal numbers because they will appear to be octal numbers. Fortunately it won't matter for 00 through 09 because I think JS does something to allow that.  But 011 is actually the same as decimal 9.
