### ISSUE TITLE
Loader not working with Angular 4 and Google Charts v45

### ISSUE THREAD

**Issue by raymondboswel** [google/google-visualization-issues#2487]
I have two versions of my application, one migrated to Angular4 and another still on Angular 2. 

The loader does not load the google charts css and js files on the Angular4 app, unless I set the charts version to 44. The current google charts version works fine on my Angular2 app.

Unfortunately the sankey chart in my app isn't supported in v44, so I'd prefer using the latest charts version.

**Comment by dlaliberte** [comment]
If you could set up a demo (maybe on jsfiddle) and describe any errors you are seeing, that would help.  Thanks.

**Comment by raymondboswel** [comment]
@dlaliberte I created a plunker and could not reproduce the issue. I then created a vanilla application, which also did not exhibit the issue. Comparing the package.json files of the project that worked with the project that didn't, lead me to notice that the project that didn't work used zone.js 0.8.5, and the vanilla project used 0.7.8. Downgrading the zone.js of my project to 0.7.8 solved the issue for me. I'm not exactly sure where to post this issue, as it seems to be the interaction between zone 0.8.5 and the latest google charts loader.

**Comment by dlaliberte** [comment]
Thanks for reporting back.  This may help others in the future who are having similar issues.

It appears that zone.js is doing some interesting magic to accomplish its goals:  https://github.com/angular/zone.js  Basically, it is hooking into all the functions which deal with asynchronous processing, in order to zonify them, to keep track of which process is running in each zone.

I see that there is a version 0.8.7 now.  Perhaps the error in 0.8.5 was incidental, or perhaps there is some conflict with Google Charts, or the loader in particular.  I wonder if there could be interference with Google Closure which also hooks into event handling in order to avoid memory leaks.
