### ISSUE TITLE
Feeding calender chart with data failing :/

### ISSUE THREAD

**Issue by nydoo** [google/google-visualization-issues#2542]
Dear community,

I'm trying to feed my google calender chart with a string I get via AJAX.

Adding the result manually works perfectly. But if I hand the string over via AJAX and store it in an variable its telling me. Type is not array.

Error:
![error_google_chart](https://user-images.githubusercontent.com/31468896/29860950-f252355c-8d67-11e7-9c77-d0e767670259.png)

Here is my JS:

```
<html>
  <head>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
	var xmlhttp = new XMLHttpRequest();
	xmlhttp.onreadystatechange = function()
	{
		if (this.readyState == 4 && this.status == 200)
		{
			stringaddrows = this.responseText;
			google.charts.load("current", {packages:["calendar"]});
			google.charts.setOnLoadCallback(drawChart);
			function drawChart() 
			{
			   var dataTable = new google.visualization.DataTable();
			   dataTable.addColumn({ type: 'date', id: 'Date' });
			   dataTable.addColumn({ type: 'number', id: 'Won/Loss' });
			   dataTable.addRows([stringaddrows]);
			   var chart = new google.visualization.Calendar(document.getElementById('calendar_basic'));
			   var options = 
			   {
					title: "Test",
					height: 350,
			   };

			   chart.draw(dataTable, options);
			}
		}
	};
	xmlhttp.open('POST', "getchartsource.php", true);
	xmlhttp.send();
    </script>
  </head>
  <body>
    <div id="calendar_basic" style="width: 1000px; height: 350px;"></div>
  </body>
</html>
```

getchartsource.php gets me exactly this:

`[ new Date(2017,7,06),6],[ new Date(2017,7,07),2.97],[ new Date(2017,7,08),0.6],[ new Date(2017,7,10),0.79],[ new Date(2017,7,15),0],[ new Date(2017,7,15),0],[ new Date(2017,7,17),5.85],[ new Date(2017,7,26),2.54],[ new Date(2017,7,29),2.86],[ new Date(2017,7,29),0.07],[ new Date(2017,6,31),0.17]`

Anyone has an idea what is going on? Is there any kind of other data transfered when requesting it from a php-file?

Best regards!
Shinori

**Comment by nbering** [comment]
I think you need to `JSON.parse()` your response text. It's hard to tell without actually stepping through your javascript, but it seems like you're passing an array with a string in it to `.addRows()`.

**Comment by nydoo** [comment]
Yeah that is true. I'm fairly new to using Google Visualization.
What type of variable should PHP give to JavaScript in order to make sure JavaScript knows what to do with it? (Is this even possible?)

Greetings

**Comment by nbering** [comment]
Generally speaking you have 3 options for initializing your chart data.

- 2D Array (An Array of Arrays)
- Data Table Object Initializer (More on that in a moment)
- Programmatic (Structure However from Server, Manipulate with JavaScript)

2D Arrays are flexible and easy to read. Most of the documentation uses the 2D array format.

I generally use the [DataTable](https://developers.google.com/chart/interactive/docs/reference#DataTable) class and pass in an object in the constructor. You can see the format for that in the documentation at that link. It's a bit complex, but it works well because it is explicit and supports anything that the chart library supports.

The last option is the write JavaScript to convert pretty much anything into a DataTable using the addRow() or addRows() functions, etc. This is nice and flexible when you're using an external API that you don't have control of the format on, or if you're using real-time data and just need to append to an existing DataTable object.

Since your issue doesn't seem to be a bug, I'd suggest closing it. If you need further assistance, the [google-visualization](https://stackoverflow.com/questions/tagged/google-visualization) tag on Stack Overflow is a great place to ask for help. There's also [other support channels](https://developers.google.com/chart/interactive/support), including a Google Groups mailing list maintained by the team.

**Comment by nydoo** [comment]
Thank you very much. 
Since DataTables seem to be very handy when using charts in general I'll work in those. 

Thanks for the detailled advices and have a great year!
