### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by hardawayd** [google/google-visualization-issues#2613]
I keep getting a syntax error on a line in a example program. The line is:

google.charts.load('current', {'packages':['corechart']});

**Comment by nbering** [comment]
Your snippet is syntactically correct as far as I can see... are you sure it's a syntax error, and not a `Cannot read property 'foo' of undefined`, or similar?

**Comment by hardawayd** [comment]
Ok, got pass that problem but really need to know how to take aRecs and put it in the DataTable:

var url = 'http://kyoto.cob.csuchico.edu:8000/ERPsim/OData/erpsim.xsodata/Sales?$format=json&$select=SIM_ROUND,SIM_STEP,AREA,CUSTOMER_NUMBER,MATERIAL_CODE,MATERIAL_DESCRIPTION,QUANTITY,NET_PRICE,NET_VALUE,COST,CONTRIBUTION_MARGIN';
  var response = UrlFetchApp.fetch(url,options).getContentText();
// var data = JSON.parse(response.getContentText()); //parse text into json
  var data = JSON.parse(response); //parse text into json
  array = data.d.results; //log data to array
  var aHeaders = Object.keys(array[0]).filter(function(key) {
     return ! key.match(/^__/);
     });
  var aRecs = array.map(function(mApp) {
    return aHeaders.map(function(sHeader)  {
    return mApp[sHeader];
      });
    })
  aRecs.unshift(aHeaders);

I want to use the data in aRecs array instead of the date being used below and don't know how to load it.

   function drawChart() {
      var data = new google.visualization.DataTable();
      data.addColumn('string', 'Topping');
      data.addColumn('number', 'Slices');
      data.addRows([
        ['Mushrooms', 3],
        ['Onions', 1],
        ['Olives', 1],
        ['Zucchini', 1],
        ['Pepperoni', 2]
      ]);

**Comment by nbering** [comment]
Sorry, can't help you much there. I have no idea what the shape of your data is.

But if you want people to help you, I have a few suggestions to make things easier for the person helping you. First, for github specifically, put your sample code in "fenced code blocks", like this:

```js
function drawChart() {
var data = new google.visualization.DataTable();
data.addColumn('string', 'Topping');
data.addColumn('number', 'Slices');
data.addRows([
['Mushrooms', 3],
['Onions', 1],
['Olives', 1],
['Zucchini', 1],
['Pepperoni', 2]
]);
```

I usually add the language hint so GitHub doesn't have to guess for syntax highlighting, which looks like this:
````
```js
// My sample code
var foo = "bar";
```
````

This just makes it easier for anyone else to read and understand the code. Which is important, because if it's too hard to understand, very few people will take the time to try to understand your problem.

Next... the question you came here to ask about is no longer a problem for you. So please close this issue since to keep Google's bug tracker clean. The thing you came here for is solved and turned out not to be a bug in Google Charts.

Keeping that in mind - that it is not a bug - I suggest taking your issue to Stack Overflow first. There is a dedicated community there that is looking for new and interesting problems to solve. If you phrase your question well, people will take an interest, and it may become the reference for others to solve issues similar to yours in the future. It might help to browse first to see if someone already solved your problem before so that you question doesn't get quickly closed as a duplicated.

Stack Overflow has a great [guide on asking questions](https://stackoverflow.com/help/how-to-ask). Pay special attention to the section called "Help others reproduce the problem". Often while trying to help others understand your problem, you find the solution yourself. This is just a natural result of breaking down the problem into it's basic pieces.

Hope this advice helps... and good look with your data transformation.
