### ISSUE TITLE
Can't format large integers anymore.

### ISSUE THREAD

**Issue by alwynallan** [google/google-visualization-issues#2676]
The first chart on this page used to render fine.

http://powernag.com/iotclock/Status.html

The y-axis contains large integers (e.g. 1539328145748) that seem to be the problem.

**Comment by dlaliberte** [comment]
Thanks for your report.

You mean the y-axis itself appears to have no ticks displayed.   It is the number of digits that is the problem, yes, and the small range of all of the values, from 1,539,328,145,600 to a little over 1,539,328,145,800   I made a series of changes that effectively reduced the number of digits that can be displayed for the ticks, but it appears I can crank that back up to where it was before.

Note, you are getting close to the max precision of JavaScript, which is about 15 digits.

I also notice a problem with the Histogram chart's domain axis when the values are small, since it uses a default format that has not enough precision, so all buckets get tick label '0'.

I will probably put out an update in a few days.  I can't think of any workaround for the large number precision problem.

**Comment by dlaliberte** [comment]
Maybe change 'current' to '45.2' in the meantime.

**Comment by alwynallan** [comment]
Thanks Daniel!

I checked and I have 285,421 years before I overflow JavaScript's largest integer.

**Comment by alwynallan** [comment]
I noticed the fix pushed out without me changing anything. Awesome! Thanks!

**Comment by dlaliberte** [comment]
Glad to hear it is working better for you.  I set the max significant digits to 15, by the way, which is less than JavaScripts max precision.  Maybe 16 works too, but I didn't want to push my luck.
