### ISSUE TITLE
loader.js:322 Uncaught Error: Module "visualization" is not supported.

### ISSUE THREAD

**Issue by AntipovAndrey** [google/google-visualization-issues#2793]
Seems like a recent release broke the loader.js, I'm getting an error when using `visualization`:
```
loader.js:322 Uncaught Error: Module "visualization" is not supported.
    at Object.google.v.w.H.Gi (loader.js:322)
    at Object.google.v.w.H.Zh [as load] (loader.js:324)
    at servers:426
```

It looks like there's a missing `break` for `case: "visualization"` in this switch case:
```
switch(c[0]){case "maps":google.v.w.H.gn.apply(google.v.w.H,T.cd(c));break;case "elements":google.v.w.H.en.apply(google.v.w.H,T.cd(c));break;case "visualization":google.v.load.apply(google.v,T.cd(c));default:google.v.w.H.Gi.apply(google.v.w.H,T.cd(c))}};
```
The issue is gone if I add the missing `break` here.

**Comment by lizard2010** [comment]
For me fixed by change loader from 
  'https://www.gstatic.com/charts/loader.js' 
back to 
  'https://www.google.com/jsapi'

**Comment by dlaliberte** [comment]
You are right.  There was an update of the loader, and I did forget a break in the switch for the 'visualization' case when you use google.load() instead of google.charts.load().  Fortunately it didn't affect so many users, and it will be fixed within an hour.

In case you are curious, the new version supports more of the other modules that the old jsapi loader would load for you, such as jquery.  The old jsapi loader will soon always redirect to the new loader.
