### ISSUE TITLE
Support for visualization version 1

### ISSUE THREAD

**Issue by Goico91** [google/google-visualization-issues#2833]
Hello,

First of all I think this Issue is related with this one: https://github.com/google/google-visualization-issues/issues/2832. 

Because since a few weeks our app is not loading correctly the Visualization module. We are using the first url: https://www.google.com/jsapi and using the first version and the error that we are receiving is:
`Load timeout for modules: goog!visualization,1,packages:[corechart]_unnormalized37,goog!visualization,1,packages:[corechart],async!`

However the different with the issue https://github.com/google/google-visualization-issues/issues/2832 is that because it's a really old application We can't update the code because it use a really old Cordova version and Apple is not going to allow to upload a new version because old Cordova versions use a WebView that Apple is forbidden. So We have a huge problem because right now the app is not working.

So, there is any why to allow again the support for this domain (https://www.google.com/jsapi) and version(1)?

Thanks for all,

**Comment by dlaliberte** [comment]
The jsapi loader, and the server it is running on, has been on the chopping block for several years.  We've been keeping it alive much longer than it deserved, and most services that depended on it have moved on to various replacements.

We will probably leave the redirect of jsapi in place, but it is possible to modify the new loader to handle more special cases that the jsapi loader supported.  But to do so, I'll need to find out the details of how you are using the jsapi loader, and what is going wrong with the redirect to the new loader.

**Comment by tecssil** [comment]
Any thoughts on this? I have the same problem, I'm redering charts into a PDF, but the loader is not able to "load" anymore. I was using the old jsapi and google.load, I made the changes as google stayed in the release and I got no charts on the PDF, it will reander on web though. I tried several workarounds and no luck yet

**Comment by dlaliberte** [comment]
If you can, please try to update how you load the visualization library, as documented here:
   https://developers.google.com/chart/interactive/docs/basic_load_libs#update-library-loader-code

If you cannot update your web page, then please provide enough details about how you are using the jsapi loader so we might be able to tell whether your old usage can be made to work in the new loader.   Specify your full jsapi URL, your google.load call and your google.setOnLoadCallback call.  Also, if you are using jquery or similar to control when these calls are made, please specify.  Point to your actual web page if you can

**Comment by Goico91** [comment]
Hi,

Yes sorry, I will give you more details of the app and our problems.

It's a mobile application built with Backbone & Marionette, with Require.js as a dependency management and package with Cordova to build the app.

To add the library as a dependency, Require.js allows you to write directly `goog!visualization,1,packages:[corechart]`
to load all what you need from Google chart library, this go to a module that recibes this params and load as a: 
`google.charts.load(data.moduleName, settings);`
from 
`https://www.google.com/jsapi`

However since this URL redirect to the new one or because the first version is not supported the app stop working because Require.js couldn't load the dependency, and right now our app in production environment stop working.

The solution will be change this dependency, but here is where we have the next problem. A few months ago Apple stop uploading to their market apps built with UIWebView (old Cordova versions) and forcing you to use WKWebView (added in the last Cordova version), so updating all dependencies from our app and the Cordova version is not something quickly and we will spend a few days doing it, so right now our fastest solution was to maintenance the library version and meanwhile update to app to all new versions.

I don't know if there is another solution and if is able to put back that version of your library.
Thanks for all,

**Comment by dlaliberte** [comment]
One possible failure relates to the use of the autoload parameter of the jsapi URL.  This parameter must now have a properly url encoded, strict JSON formatted value, since we do not eval the parameter in the new loader for safety reasons, nor do we have an expression parser.  

Another possible failure relates to not waiting for the library to load by using a 'callback' setting or calling the google.setOnLoadCallback function.  The jsapi loader was sometimes able to load the library more quickly, but now with the redirect, there is no way we can avoid the asynchronous loading delay. So there is nothing we can do about this either. 

Yet another possible failure relates to pages that depend on internal undocumented features of the jsapi loader, which are not supported in the new loader.  E.g. there was one function call that loaded an arbitrary URL, which we will not support in the new loader for safety reasons.

We have been pushing out the redirect and rolling it back periodically several times over the last few months, so we were hoping more people would have noticed the failures by now and reported problems or made adjustments.    For problems that we have a chance of working around, a rollback and change to the new loader might make sense.  For problems that cause a severe outage that you have a chance of fixing with some more time, let us know your situation.

**Comment by Goico91** [comment]
Ok, dlaliberte don't worry We will talk with our customer and find another solutions, We were asking only if it was an easy implementation. 

Thanks for all, I close the issue!
