### ISSUE TITLE
Charts failing: 404 We're sorry but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.

### ISSUE THREAD

**Issue by neil-amp** [google/google-visualization-issues#2836]
Suddenly none of our charts / datatables are working and it seems to be due to this page returning a 404:

https://www.google.com/uds/?file=visualization&v=1&packages=corechart%2Ctable

When I go to the page I see the message:

We're sorry...
... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.

Just wondering if this is a random glitch on Google's side or something specific with our application?

**Comment by lyamone** [comment]
Same problem here! We got a 404 error code when trying to get visualizations.
Can somebody take a look on this?

**Comment by dlaliberte** [comment]
The UDS server is being turned down.  That is the server that *used* to respond to requests for library modules with URLs like https://www.google.com/uds/....  But the jsapi loader that was *supposed* to be used to initiate loading of the library modules now redirects to the new loader, so there should be no more direct requests to the UDS server.   

The 404 error codes might be due to misbehaving caches, which should clear up on its own, or you can force your browser to clear its cache.  Caching servers are more difficult to deal with since they are typically invisible.  Or perhaps some pages bypass the jsapi loader and make direct links to the library modules, but the only fix there is to fix those pages.

The best solution is to stop using the jsapi loader.  Please update how you load Google Charts by following the instructions at:  https://developers.google.com/chart/interactive/docs/basic_load_libs#update-library-loader-code

**Comment by neil-amp** [comment]
Thanks, it seems the issue is we were including a local copy of jsapi.js switching to <script type="text/javascript" src="https://www.google.com/jsapi"></script> fixed the issue. Will look in to switching to the new form of loading too.
