### ISSUE TITLE
cannot load visualization orgchart script

### ISSUE THREAD

**Issue by makr8100** [google/google-visualization-issues#2837]
When trying to use visualization our page doesn't load.  The XHR shows an error on the following GET URI:
https://www.google.com/uds/?file=visualization&v=1.0&packages=orgchart&async=2

When opening that URI in the browser we get:

We're sorry...
... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.
See Google Help for more information.

![Screenshot_20200701_131514](https://user-images.githubusercontent.com/5727352/86277837-04064200-bb9d-11ea-8143-491662036c11.png)

We have tested at multiple locations with the same results.

**Comment by dlaliberte** [comment]
The UDS server is being turned down. That is the server that _used_ to respond to requests for library modules with URLs like https://www.google.com/uds/.... But the jsapi loader that was _supposed_ to be used to initiate loading of the library modules now redirects to the new loader, so there should be no more direct requests to the UDS server.

The 404 error codes might be due to misbehaving caches, which should clear up after some period of time, or you can force your browser to clear its cache. Caching servers are more difficult to deal with since they are typically invisible. Or perhaps some pages bypass the jsapi loader and make direct links to the library modules, but the only fix there is to fix those pages.  Another cause of this kind of problem is using a local copy of the jsapi loader.  

The best solution is to stop using the jsapi loader. Please update how you load Google Charts by following the instructions at: https://developers.google.com/chart/interactive/docs/basic_load_libs#update-library-loader-code

**Comment by makr8100** [comment]
We were using a local copy of jsapi.  It was as simple as a drop-in replacement.  Thank you!
