### ISSUE TITLE
V Axis Not Disappearing

### ISSUE THREAD

**Issue by collodrollo** [google/google-visualization-issues#2877]
https://jsfiddle.net/ucs629fh/84/

**Comment by dlaliberte** [comment]
That vertical axis line is really the horizontal axis baseline.  You can hide it by setting the hAxis baselineColor to 'none':

` hAxis: {
              	 textPosition: 'none',
  							 minValue: 0,
                 gridlines: {
                 	 color: 'none'
                 },
                 baselineColor: 'none'
              },`

**Comment by collodrollo** [comment]
Ahh, I see. It's the horizontal axis because the horizontal bar graph is treated as a vertical bar graph rotated. Thanks a lot.

**Comment by dlaliberte** [comment]
> Ahh, I see. It's the horizontal axis because the horizontal bar graph is treated as a vertical bar graph rotated. Thanks a lot.

Not quite right.  It is a horizontal axis option because the baseline and gridlines for an axis go in the 'other' direction.  Horizontal axis gridlines, corresponding to horizontal ticks, are drawn vertically, etc.   This is a common confusion, and we should try to make it clear somewhere in the documentation, without having to repeat it for every chart type.
