### ISSUE TITLE
Timeline cannot be rendered with upcoming version (v51) due to dygraph-tickers-combined.js cannot be found

### ISSUE THREAD

**Issue by seazenith** [google/google-visualization-issues#2913]
When we testing the **upcoming** version (v51) on **Timeline** visualization, we found it cannot be rendered due to **dygraph-tickers-combined.js** cannot be found (404) error. But it works fine with **current** version (v50).

This issue can also be reproduced using the official sample from: https://developers.google.com/chart/interactive/docs/gallery/timeline, and change the version from "current" to "upcoming", see here: https://jsfiddle.net/psfartu5/
![image](https://user-images.githubusercontent.com/6406414/122715874-21e02180-d29c-11eb-919a-7678b97254ed.png)

So it seems **dygraph-tickers-combined.js** was removed unintentionally, would you please help to confirm and fix it? Thanks a lot.

**Comment by VDidyk** [comment]
The same issue. Chart doesn't work

![image](https://user-images.githubusercontent.com/20489106/122716990-a8343d80-d273-11eb-8486-b42b88e68b82.png)

**Comment by seazenith** [comment]
Find error in more chart types, they all share the same issue, it seems the **third_party** folder was removed in v51.
![image](https://user-images.githubusercontent.com/6406414/122741051-28c85d80-d2b7-11eb-8ce9-805f4e152025.png)

**Comment by hotear** [comment]
Also have this problem.  None of the graphs are showing up on my website anymore.  Please fix asap. Thanks.

**Comment by dlaliberte** [comment]
First of all, I am glad to see so many people testing the 'upcoming' version, though some people appear to be unaware that they have been doing that :)

The problem was due to a change unrelated to the third_party libraries which nevertheless broke the deployment of the third_party libraries.  I have fixed this now, so all charts should be working as before (or maybe within an hour or two from now, depending on cache expiration).

**Comment by hotear** [comment]
Like you say, if I have been testing the upcoming version I was unaware that I was doing so.  How do I force it to use the previous version in that case?  In my page I am simply doing the following:
    google.load("visualization", "1.1", {packages:["line","bar","gauge"], callback: initChart});
One day it was working, the next it stopped.

**Comment by dlaliberte** [comment]
For those still using the old loader, loading jsapi, and calling google.load, if you load "1.1", that is mapped to 'uploading', since they served the same purpose.  Version "1" was the 'current' release.  

But you really should change your loader, by following the [instructions on the loader documentation page](https://developers.google.com/chart/interactive/docs/basic_load_libs#update-library-loader-code).

**Comment by seazenith** [comment]
> First of all, I am glad to see so many people testing the 'upcoming' version, though some people appear to be unaware that they have been doing that :)
> 
> The problem was due to a change unrelated to the third_party libraries which nevertheless broke the deployment of the third_party libraries. I have fixed this now, so all charts should be working as before (or maybe within an hour or two from now, depending on cache expiration).

@dlaliberte thanks a lot for the quick response and fix.

**Comment by carlzbg-cyber** [comment]
I had the same problem. The charts disappeared and "No loader available" was shown in red.
We have been using ng-google-chart.js
I had to modify the source code to load www.gstatic.com/charts/loader.js instead of www.google.com/jsapi
Now the charts are showing again
